# Generated by Django 3.1.4 on 2020-12-04 11:23

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('HP', '0008_auto_20201204_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='role2',
        ),
        migrations.AlterField(
            model_name='account',
            name='role',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('no rights', 'no rights'), ('Cleaner', 'Cleaner'), ('Manager', 'Manager'), ('System Admin', 'System Admin'), ('General Director', 'General Director'), ('Master', 'Master')], default='no rights', max_length=120),
        ),
    ]
