# Generated by Django 3.1.4 on 2020-12-04 11:28

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('HP', '0009_auto_20201204_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('no rights', 'no rights'), ('Cleaner', 'Cleaner'), ('Manager', 'Manager'), ('System Admin', 'System Admin'), ('General Director', 'General Director'), ('Master', 'Master')], default='no rights', max_length=120),
        ),
        migrations.AlterField(
            model_name='document',
            name='mark',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('all', 'all'), ('managers', 'managers'), ('middle', 'middle'), ('secret', 'secret'), ('top secret', 'top secret')], max_length=100),
        ),
    ]
